### ISSUE TITLE
why you style html and .container.?

### ISSUE THREAD

**Issue by mboveiri** [poldelmengo/beam#1]
Hi.
They are used extensively, and not-safe to be re-style by a framework.

**Comment by pldg** [comment]
Hi, as I wrote in [documentation](https://pldg.github.io/beam/) I use a [css reset](https://stackoverflow.com/questions/11578819/css-reset-what-exactly-does-it-do) to avoid layout alignment problems. As you can see from [line 23 to line 39](https://github.com/pldg/beam/blob/master/beam.css#L23-L39) it's very minimal. Also other popular css framework like [bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L38-L51) use the same technique. In documentation is also stated that you can re-style the `.container` if you wish.
